apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d1f3lwy8x-go
  janus-idp.io/tekton: d1f3lwy8x-go
  backstage.io/kubernetes-id: d1f3lwy8x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d1f3lwy8x-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
